### ISSUE TITLE
WASM Compatibility

### ISSUE THREAD

**Issue by tonygoldcrest** [GenericMadScientist/SightRead#1]
Hi, thank you for this library, it's great!

I'd really like to use it for an electron app I'm building that converts CH drum charts to sheet music that you can play along to. So I was trying to compile this library as a WASM module.

Been trying to use [embind](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html) to bind APIs, but been stuck at some parts of the codebase using `std::set` that Emscripten doesn't provide bindings for.
Unfortunately, my C++ knowledge is not very good so I'm not sure what I need to do to enable things like that.

It sounds like a lot of work to make it wasm compatible, but on the other hand, wasm modules can be used with different languages, so I thought I'd ask whether it's possible to do so. It would really enable devs like me to use this library for different applications.

In any case, this repo provides some great insights into how to parse midi, so if it's impossible to make a wasm module, I can use it as a resource to build my own js parser.

**Comment by GenericMadScientist** [comment]
I'm quite happy to make this Wasm compatible, I don't do any C++ black magic so it should be possible.

I'd be surprised if Emscripten couldn't handle `std::set`, however it would make sense to me if it was choking on the [contains method](https://en.cppreference.com/w/cpp/container/set/contains) since it only got added in C++20. Try passing `-std=c++20` and see if that solves it.

Failing that, if you can provide a minimal failing example and the error message then I'll be happy to give it a look.

**Comment by tonygoldcrest** [comment]
Thanks for the quick reply!

I don't fully understand what I'm doing, but it seems that Emscripten [provides mappings](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html#built-in-type-conversions) for vector (register_vector) and map (register_map), but not for std::set.

Therefore, when I try to bind permit_instruments function like that:
```
#include <emscripten/bind.h>

#include "sightread/midiparser.hpp"
#include "sightread/songparts.hpp"
#include "sightread/chartparser.hpp"
#include "sightread/metadata.hpp"
#include "sightread/detail/chart.hpp"
#include "sightread/detail/chartconverter.hpp"

using namespace emscripten;

EMSCRIPTEN_BINDINGS(Sightread) {
    class_<SightRead::MidiParser>("MidiParser")
        .constructor<SightRead::Metadata>()
        .function("hopo_threshold", &SightRead::MidiParser::hopo_threshold)
        .function("permit_instruments", &SightRead::MidiParser::permit_instruments)
        .function("parse_solos", &SightRead::MidiParser::parse_solos)
        .function("parse", &SightRead::MidiParser::parse)
        ;

	value_object<SightRead::Metadata>("Metadata")
        .field("name", &SightRead::Metadata::name)
        .field("artist", &SightRead::Metadata::artist)
        .field("charter", &SightRead::Metadata::charter)
        ;

	enum_<SightRead::Instrument>("Instrument")
		.value("Guitar", SightRead::Instrument::Guitar)
		.value("GuitarCoop", SightRead::Instrument::GuitarCoop)
		.value("Bass", SightRead::Instrument::Bass)
		.value("Rhythm", SightRead::Instrument::Rhythm)
		.value("Keys", SightRead::Instrument::Keys)
		.value("GHLGuitar", SightRead::Instrument::GHLGuitar)
		.value("GHLBass", SightRead::Instrument::GHLBass)
		.value("GHLRhythm", SightRead::Instrument::GHLRhythm)
		.value("GHLGuitarCoop", SightRead::Instrument::GHLGuitarCoop)
		.value("Drums", SightRead::Instrument::Drums)
		;
}
```

And then use it from js:

```
const a = new Module.MidiParser({name: 'hello', artist: 'foo', charter: 'bar'});
a.permit_instruments();
```

I get this error:

```
"UnboundTypeError"
"Cannot call MidiParser.permit_instruments due to unbound types: NSt3__23setIN9SightRead10InstrumentENS_4lessIS2_EENS_9allocatorIS2_EEEE"
```

which tells me that in order to bind this function I need to implement `register_set` similar to `register_vector`, which I think would be a difficult task for me considering my C++ knowledge.

**Comment by tonygoldcrest** [comment]
Would it be helpful if I open a PR with my progress?

**Comment by GenericMadScientist** [comment]
A PR would be helpful, yes.

In this case it's complaining that `std::set<SightRead::Instrument>` is unbound, perhaps you could just do a normal `class_<std::set<SightRead::Instrument>>` and add only the methods you need. That way you don't have to contend with templates, at least.

Alternatively, if you tell me what operations you would like to do on the set (I assume adding elements is a given, anything else?) then I can try to write the binding for you.

**Comment by tonygoldcrest** [comment]
That totally works, thanks for the idea!

**Comment by tonygoldcrest** [comment]
As for what operations I'd like to use, I think the question is rather what exactly do you need to expose from the library for the workflow that you have in CHOpt?
The workflow I think would be something like:
1) [JS] Read the file
2) [Wasm] Pass the data to the parser, setting up drums as target
3) [Wasm -> JS] Get the data necessary to draw sheet music (notes, bpm shifts, etc)

Does this use case requires exposing the majority of the library?
